name: Node.js CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Typecheck TypeScript
      run: npm run type-check
      
    - name: Run linter
      run: npm run lint
      
    strategy:
      matrix:
        node-version: [14.x, 16.x]
