name: Node.js CI

on: [push, pull_request]

env:
  DATABASE_URL: "${{ secrets.DATABASE_URL }}"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
  CLERK_SECRET_KEY: "${{ secrets.CLERK_SECRET_KEY }}"
  UPSTASH_REDIS_REST_URL: "${{ secrets.UPSTASH_REDIS_REST_URL }}"
  UPSTASH_REDIS_REST_TOKEN: "${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Use Node.js 16.13.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        
    - name: Install dependencies
      run: npm ci
      
    - name: Typecheck TypeScript
      run: npm run type-check
      
    - name: Run linter
      run: npm run lint
